[package]
name = "upload-images"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.4.1"
log = "0.4.14"
serde = "1.0.130"
serde_json = "1.0.59"
simple_logger = "1.13.0"
tokio = "1.8.4"

[dev-dependencies]
cargo-watch = "8.1.1"